version: 0.2

env:
  git-credential-helper: yes
phases:
  build:
    commands:
      - zip -r hathor-wallet-service.zip .
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
    - hathor-wallet-service.zip
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
