version: 0.2

env:
  git-credential-helper: yes
phases:
  build:
    commands:
      - echo "source code will be uploaded to S3"
      - echo $CODEBUILD_SOURCE_VERSION
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
    - '**/*'
    # - hathor-wallet-service.zip
  name: hathor-wallet-service-source
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
