version: 0.2

env:
  git-credential-helper: yes
  variables:
    NODE_ENV: "production"
    NETWORK: "testnet"
    MAX_ADDRESS_GAP: 20
    WALLET_CONN_LIMIT: 10
    BLOCK_REWARD_LOCK: 300
    CONFIRM_FIRST_ADDRESS: true
    AWS_VPC_DEFAULT_SG_ID: "sg-e3dbfc8f"
    AWS_SUBNET_ID_1: "subnet-0a0e14dd37306ab3d"
    AWS_SUBNET_ID_2: "subnet-05de110f4ea8d425b"
    AWS_SUBNET_ID_3: "subnet-0de32ea8c0f64f1bc"
  secrets-manager:
    # https://eu-central-1.console.aws.amazon.com/secretsmanager/home?region=eu-central-1#!/listSecrets
    ADMINTOKEN: "WalletService/dev:admintoken"
    AUTH_SECRET: "WalletService/dev:auth_secret"
    PROD_DB_NAME: "WalletService/rds/dev:dbname"
    PROD_DB_USERNAME: "WalletService/rds/dev:username"
    PROD_DB_PASSWORD: "WalletService/rds/dev:password"
    PROD_DB_HOSTNAME: "WalletService/rds/dev:host"
    PROD_DB_PORT: "WalletService/rds/dev:port"
    REDIS_URL: "WalletService/redis/dev:url"
    REDIS_PASSWORD: "WalletService/redis/dev:password"
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      nodejs: 14
      # name: version
    commands:
      - npm i --also=dev
  pre_build:
    commands:
      - ls -lt
  build:
    commands:
      - make migrate
      - make deploy-lambdas-dev-testnet
  #post_build:
    #commands:
      # - command
      # - command
#artifacts:
#  files:
#    - application.zip
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
