version: 0.2

env:
  git-credential-helper: yes
phases:
  build:
    commands:
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - |
        if expr "${CODEBUILD_WEBHOOK_HEAD_REF#refs/tags/}" : "v.*" >/dev/null; then
          echo "${CODEBUILD_WEBHOOK_HEAD_REF#refs/tags/}" > git_ref_to_deploy
        fi
      - |
        if expr "${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/}" : "master" >/dev/null; then
          echo "${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/}" > git_ref_to_deploy
        fi
      - |
        if expr "${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/}" : "dev" >/dev/null; then
          echo "${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/}" > git_ref_to_deploy
        fi
      - echo "source code will be uploaded to S3"

  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
    - '**/*'
    # - hathor-wallet-service.zip
  name: hathor-wallet-service-source
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
